version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.8.6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
  kibana:
    image: kibana:6.8.6
    ports:
      - "5601:5601"
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /tmp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - devops
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - devops
  jenkins:
    image: jenkinsci/blueocean
    user: "root"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home
    ports:
      - "8085:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - devops
networks:
  devops:
    driver: bridge




