version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.8.6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
  kibana:
    image: kibana:6.8.6
    ports:
      - "5601:5601"
  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - pgvol:/var/lib/postgresql/data
    networks:
      - devops
  pgadmin:
    restart: always
    image: dpage/pgadmin4:5.5
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - devops
  jenkins:
    image: jenkinsci/blueocean:1.24.8
    user: "root"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home
    ports:
      - "8085:8080"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - devops
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    ports:
      - "8180:8080"
      - "8181:8443"
      - "9990:9990"
    restart: always
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./keycloak-data/realm-api.json:/opt/jboss/keycloak/realm-api.json
    depends_on:
      - postgres
    networks:
      - devops
networks:
  devops:
    driver: bridge
volumes:
  pgvol:
  data01:





