version: '3'

services:
  elasticsearch:
    image: arm64v8/elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - pgvol:/var/lib/postgresql/data
    networks:
      - devops
  pgadmin:
    restart: always
    image: dpage/pgadmin4:5.5
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - devops
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true
    user: root
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
    - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    - /var/run/docker.sock:/var/run/docker.sock  # Give Jenkins access to Docker
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - devops
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    ports:
      - "8180:8080"
      - "8181:8443"
      - "9990:9990"
    restart: always
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./keycloak-data/realm-api.json:/opt/jboss/keycloak/realm-api.json
    depends_on:
      - postgres
    networks:
      - devops
networks:
  devops:
    driver: bridge
volumes:
  pgvol:
  data01:
  es_data: # Elasticsearch data will be stored in this named volume
      driver: local
  jenkins_home:




